docker/moby: update to 23.0.1
Issue: LINCD-10318

Update docker and docker-moby to 23.0.1.
The contents are mostly from current docker-ce_git and docker-moby_git.

(LOCAL REV: NOT UPSTREAM) -- WRLinux Specific Patch

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>

Rebased on 20230618.

Signed-off-by: Kai Kang <kai.kang@windriver.com>

Rebased on 20231114.

Signed-off-by: Kai Kang <kai.kang@windriver.com>

diff --git a/recipes-containers/docker/docker-moby/0001-cli-use-external-GO111MODULE-and-cross-compiler.patch b/recipes-containers/docker/docker-moby/0001-cli-use-external-GO111MODULE-and-cross-compiler.patch
--- a/recipes-containers/docker/docker-moby/0001-cli-use-external-GO111MODULE-and-cross-compiler.patch
+++ b/recipes-containers/docker/docker-moby/0001-cli-use-external-GO111MODULE-and-cross-compiler.patch
@@ -1,27 +1,33 @@
-From 839b7be681c7ee9349737c10a144c66131b36d7a Mon Sep 17 00:00:00 2001
-From: Chen Qi <Qi.Chen@windriver.com>
-Date: Wed, 18 May 2022 20:26:17 -0700
+From 650c882d3c53db118b01dd5e15fa1bc0ddaa36f1 Mon Sep 17 00:00:00 2001
+From: Bruce Ashfield <bruce.ashfield@gmail.com>
+Date: Thu, 15 Apr 2021 11:28:05 -0400
 Subject: [PATCH] cli: use external GO111MODULE and cross compiler
 
-Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
----
- cli/scripts/build/binary | 4 +---
- 1 file changed, 1 insertion(+), 3 deletions(-)
+Upstream-Status: Inappropriate [embedded specific]
 
-diff --git a/cli/scripts/build/binary b/cli/scripts/build/binary
-index f12a5ac..35ffc06 100755
---- a/cli/scripts/build/binary
-+++ b/cli/scripts/build/binary
-@@ -73,8 +73,6 @@ fi
+Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
+---
+ git/cli/scripts/build/binary | 3 +--
+ 1 file changed, 1 insertion(+), 2 deletions(-)
+
+Index: git/cli/scripts/build/binary
+===================================================================
+--- git.orig/cli/scripts/build/binary
++++ git/cli/scripts/build/binary
+@@ -13,8 +13,6 @@
  
  echo "Building $GO_LINKMODE $(basename "${TARGET}")"
  
 -export GO111MODULE=auto
 -
--go build -o "${TARGET}" -tags "${GO_BUILDTAGS}" --ldflags "${GO_LDFLAGS}" ${GO_BUILDMODE} "${SOURCE}"
-+${GO} build -o "${TARGET}" -tags "${GO_BUILDTAGS}" --ldflags "${LDFLAGS}" ${GO_BUILDMODE} "${SOURCE}"
+ if [ "$(go env GOOS)" = "windows" ]; then
+   if [ ! -x "$(command -v goversioninfo)" ]; then
+     >&2 echo "goversioninfo not found, skipping manifesting binary"
+@@ -24,6 +22,6 @@
+   fi
+ fi
+ 
+-(set -x ; go build -o "${TARGET}" -tags "${GO_BUILDTAGS}" -ldflags "${GO_LDFLAGS}" ${GO_BUILDMODE} "${SOURCE}")
++(set -x ; ${GO} build -trimpath -o "${TARGET}" -tags "${GO_BUILDTAGS}" -ldflags "${GO_LDFLAGS}" ${GO_BUILDMODE} "${SOURCE}")
  
  ln -sf "$(basename "${TARGET}")" "$(dirname "${TARGET}")/docker"
--- 
-2.36.0
-
